### PR TITLE
Add Tested with Confidence badge, closes #89

### LINKED ISSUE #89: Add Tested with Confidence Badge

### PR DESCRIPTION
**Pull request by dmfs**

### CODE REVIEW

**Comment by dmfs** [comment]
@sschuberth I don't use Conventional Commits myself because I typically use ticket type/labels to decide about the change type. Please let me know if these changes work for you.

**Comment by dmfs** [comment]
published in 0.25.0

**Comment by dmfs** [comment]
published as 0.25.0 now

**Comment by sschuberth** [comment]
> Please let me know if these changes work for you.

Sorry, but what change in this PR is related to Conventional Commits?

**Comment by sschuberth** [comment]
> > Please let me know if these changes work for you.
> 
> Sorry, but what change in this PR is related to Conventional Commits?

Ah, I guess the comment was supposed to go to https://github.com/dmfs/gver/issues/78, right?

**Comment by dmfs** [comment]
Oh yes. My comments were intended to go to #80/#78 :laughing:

**Pull request merged**
