### PR TITLE
feat: Refuse tagging when the Git working tree has uncommitted changes

### LINKED ISSUE #4: prevent tagging of versions in dirty repositories

### PR DESCRIPTION
**Pull request by sschuberth**
Fixes #4.

### CODE REVIEW

**Comment by dmfs** [comment]
This needs an integration test like in https://github.com/dmfs/gver/blob/main/gradle-plugin/src/test/java/org/dmfs/gradle/gver/tasks/TagReleaseTaskTest.java#L95 for instance. It should be sufficient to create an empty file in the code block passed to `given`. Adjusting the expectation in line https://github.com/dmfs/gver/blob/main/gradle-plugin/src/test/java/org/dmfs/gradle/gver/tasks/TagReleaseTaskTest.java#L110 might be a bit tricky though. I'll look into that and make a proposal.

**Comment by sschuberth** [comment]
Weird, for some reason (only) `import static org.dmfs.gradle.gver.utils.Matchers.given;` does not resolve for me in IntelliJ IDEA. Any hint what might be causing this?

image

PS: Have you considered migrating this project to Kotlin? Esp. for the DSL support that might make sense.

**Comment by dmfs** [comment]
That class is generated from the `Given` class. You will have to compile the test classes first. I have plans to replace that code but didn't have time to do that yet.

**Comment by dmfs** [comment]
I haven't considered migrating to Kotlin yet. I'll look into that. Not sure if that solves my main issues with the way you build DSLs in Groovy though, because I believe the core concept is similar in Kotlin.

**Comment by dmfs** [comment]
Actually, this test is probably better suited as a starting point: https://github.com/dmfs/gver/blob/main/gver-dsl/src/test/java/org/dmfs/gver/git/SuffixesTest.java#L50
It initializes a repository and creates a file to make it dirty. Also it uses the new assertion framework Confidence instead of Hamcrest.

**Comment by dmfs** [comment]
I'll rewrite the gradle task integration tests to use the Confidence framework. That should simplify them a bit. #83

**Comment by sschuberth** [comment]
> Not sure if that solves my main issues with the way you build DSLs in Groovy though, because I believe the core concept is similar in Kotlin.

I don't know what issues you're facing with Groovy, but for a simple starter with a Kotlin DSL you may want to have a quick look at https://kotlinlang.org/docs/type-safe-builders.html.

**Comment by sschuberth** [comment]
I've stumbled over this comment:

https://github.com/dmfs/gver/blob/2337c917ded59da34ee63ff816b0e4cd20bf26fb/gradle-plugin/src/test/java/org/dmfs/gradle/gver/tasks/TagReleaseTaskTest.java#L68-L69

Is this still the way to go to verify that a tag hasn't been created, or should I now check for the exception being thrown as you outlined [here](https://github.com/dmfs/gver/pull/82#pullrequestreview-1606472410), or do both?

**Comment by dmfs** [comment]
> Ah. Would be nice if no such manual step would be required, though.

Yes, I'll get rid of this.

Thanks I'll check out the links.

> Is this still the way to go to verify that a tag hasn't been created, or should I now check for the exception being thrown as you outlined https://github.com/dmfs/gver/pull/82#pullrequestreview-1606472410, or do both?

Both. Actually the test already fails if no exception is thrown: https://github.com/dmfs/gver/blob/main/gradle-plugin/src/test/java/org/dmfs/gradle/gver/tasks/TagReleaseTaskTest.java#L64 It's just not the nice declarative way yet.
So yes, the test verifies that the task fails *and*  that no additional tags have been created.

**Comment by dmfs** [comment]
You may have noticed that I've updated the `TagTaskTest` with a new Confidence based implementation that should be more straight forward.

Regarding DSLs and Kotlin, my main "problem" with both, Groovy and Kotlin is that their closure-based DSLs require mutable objects and side-effects to work, both of which I try to avoid in my code. For instance, the Confidence framework test DSL is entirely built on immutable objects without side effects. I find it easier to work with immutable objects that don't have side effects and they are also easier to test.

I decided to use this DSL style because that how Gradle users are used to it and because anything else probably would require adding import statements to the Gradle build file, which would be a bit awkward. Admittedly, Kotlin's type safety might make it a bit easier to work with. I'll give Kotlin a try and see how it works with my (still groovy based) Gradle build files.

**Comment by sschuberth** [comment]
> You may have noticed that I've updated the `TagTaskTest` with a new Confidence based implementation that should be more straight forward.

Yes, I've seen these updates. But THB I'm having difficulties seeing through this deeply nested syntax... that looks almost like Lisp / Scheme 😆 I'm more used to tests in simple AAA layout like [this](https://github.com/oss-review-toolkit/ort/blob/31d1c8774823919a3e84a26c75723de005ecff8b/utils/ort/src/test/kotlin/DeclaredLicenseProcessorTest.kt#L64-L75). But I'll try to get my head around the syntax 😉

**Comment by dmfs** [comment]
😅 the Lisp comparison is indeed quite fitting. In contrast to AAA, which is a very imperative concept, the Confidence framework (just like Hamcrest) follows functional ideas.

The basic idea is to compose a function (from other functions) that, given an instance of a specific type, return `true` if that instance has the qualities/behavior as described by the composition and `false` otherwise. Needless to say that his works best with immutable objects, but mutation can be tested too as the tests demonstrate. The functional approach allows you to express even very complex behavior with relatively simple components. 

`assertionThat` does nothing but passing the given instance to the quality that describes the expected behavior and throws an `AssertionException` when it didn't pass the test.

One of the goals is to get rid of any imperative code in tests, because that's typically not testable itself.

**Comment by sschuberth** [comment]
> But I'll try to get my head around the syntax 😉

Ok, I give up. I started by copying the `gitTagRelease_no_tag_on_feature_branch` assertion to a new `gitTagRelease_no_tag_when_dirty` assertion, but then I cannot find a valid syntax to combine this with creating an untracked file like in `illegal_commit_fails`.  Can you give me a hint? Or do you want to do it yourself?

**Comment by dmfs** [comment]
the idea is to create a decorator to the Repository Resource that "initializes" the Repository. There is a ticket for such a decorator: saynotobugsorg/confidence#70
Until that's implemented you help yourself with this pattern: https://github.com/dmfs/gver/blob/main/gver-dsl/src/test/java/org/dmfs/gver/git/SuffixesTest.java#L51
You essentially provide another resource that's like the original one, but executes a piece of imperative code before it returns the resource.
Let me know if you don't feel like diving into declarative testing today and I'll do this myself.

**Comment by dmfs** [comment]
ah, I just noticed that the `illegal_commit_fails` uses the same pattern. My description probably wasn't that helpful then.

The `withResource` Assertion takes some kind of `Callable` (not exactly a `Callable` but a similar interface) that returns the resource used by the test. Before the assertion is verified `withResource`, calls the `Callable` and passes the result to the function in the second argument to get the actual `Assertion` that's then verified afterwards it closes the resource.

Again, in this case we return the original resource that's been passed as an argument and just operate on it.

**Comment by sschuberth** [comment]
> ah, I just noticed that the `illegal_commit_fails` uses the same pattern. My description probably wasn't that helpful then.

Yeah, unfortunately that's the case.

One thing that confuses me in the existing code is that the temp dir created at

https://github.com/dmfs/gver/blob/efe33e5fbb002dd722140793d36b57af6f727695/gradle-plugin/src/test/java/org/dmfs/gradle/gver/tasks/TagReleaseTaskTest.java#L63

seem to map to the `gradleDir` argument at

https://github.com/dmfs/gver/blob/efe33e5fbb002dd722140793d36b57af6f727695/gradle-plugin/src/test/java/org/dmfs/gradle/gver/tasks/TagReleaseTaskTest.java#L71

but `gradleDir` is not used anywhere in the code. So can't this be omitted by replacing `withResources` (plural) with `withResource` (singular)?

**Comment by dmfs** [comment]
@sschuberth to you plan to finish this or shall I?

**Comment by sschuberth** [comment]
Sorry @dmfs, I'm currently on a business trip and would appreciate if you could add the missing test. Thanks in advance!

**Comment by dmfs** [comment]
I merged this in #87 but unfortunately your authorship got lost during squashing. I'm not sure why. Normally it should be preserved. I'll check why it happened and how to prevent it next time.

**Pull request closed without merging**
